title: Life & Times of George Jetson
author: Chris Klann
email: chris@klanns.org
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Here's an awesome description for your new site here. I'm editing this
  line in _config.yml. It appears in my document head meta (for
  Google search results) and in my feed.xml site description.

# social links
twitter_username: gjetson # DO NOT include the @ character, or else the build will fail!
github_username:  cklann1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
